# Generated by Django 3.2.17 on 2023-02-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alcohol_degree', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('recipe', models.TextField()),
                ('img_url', models.URLField()),
                ('alcohol_degree', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Juice',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alcohol_degree', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CocktailSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_sub', to='api.cocktail')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_sub', to='api.sub')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_other', to='api.cocktail')),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_other', to='api.other')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailJuice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_juice', to='api.cocktail')),
                ('juice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_juice', to='api.juice')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_base', to='api.base')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_base', to='api.cocktail')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='glass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cocktail', to='api.glass'),
        ),
    ]
