# Generated by Django 3.2.17 on 2023-02-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alcohol_degree', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('recipe', models.TextField()),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CocktailJuice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_juice', to='api.cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_other', to='api.cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_sub', to='api.cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alcohol_degree', models.FloatField(default=0.0)),
                ('cocktail', models.ManyToManyField(related_name='sub', through='api.CocktailSub', to='api.Cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cocktail', models.ManyToManyField(related_name='other', through='api.CocktailOther', to='api.Cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='Juice',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cocktail', models.ManyToManyField(related_name='juice', through='api.CocktailJuice', to='api.Cocktail')),
            ],
        ),
        migrations.AddField(
            model_name='cocktailsub',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_sub', to='api.sub'),
        ),
        migrations.AddField(
            model_name='cocktailother',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_other', to='api.other'),
        ),
        migrations.AddField(
            model_name='cocktailjuice',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_juice', to='api.juice'),
        ),
        migrations.CreateModel(
            name='CocktailBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_base', to='api.cocktail')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_base', to='api.base')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='glass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cocktail', to='api.glass'),
        ),
        migrations.AddField(
            model_name='base',
            name='cocktail',
            field=models.ManyToManyField(related_name='base', through='api.CocktailBase', to='api.Cocktail'),
        ),
    ]
