# Generated by Django 3.2.13 on 2022-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('cocktail_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ddabong', models.IntegerField(default=0)),
                ('recipe', models.CharField(default='', max_length=200)),
                ('base', models.JSONField(blank=True, null=True)),
                ('sub', models.JSONField(blank=True, null=True)),
                ('juice', models.JSONField(blank=True, null=True)),
                ('other', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=30)),
                ('cocktails', models.ManyToManyField(related_name='sub_cocktail', to='api.Cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cocktails', models.ManyToManyField(related_name='other_cocktail', to='api.Cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='Juice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=30)),
                ('cocktails', models.ManyToManyField(related_name='juice_cocktail', to='api.Cocktail')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('drink_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cocktails', models.ManyToManyField(related_name='base_cocktail', to='api.Cocktail')),
            ],
        ),
    ]
