# Generated by Django 3.2.17 on 2023-02-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='glass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.glass'),
        ),
    ]
