# Generated by Django 4.0.4 on 2022-07-20 08:29

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='base',
            field=models.JSONField(blank=True, null=True, validators=[api.validators.check_amount_int]),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='juice',
            field=models.JSONField(blank=True, null=True, validators=[api.validators.check_amount_int]),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='sub',
            field=models.JSONField(blank=True, null=True, validators=[api.validators.check_amount_int]),
        ),
    ]
