# Generated by Django 3.2.17 on 2023-02-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todaycocktail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodayCocktail',
            new_name='TodayDrink',
        ),
    ]
