# Generated by Django 3.2.14 on 2022-08-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cocktail_base_alter_cocktail_juice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='img_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
