# Generated by Django 3.2.17 on 2023-02-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_todaycocktail_todaydrink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cocktail', models.ManyToManyField(related_name='hashtag', to='api.Cocktail')),
            ],
        ),
    ]
