# Generated by Django 3.2.17 on 2023-02-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cocktail_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='alcohol_degree',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sub',
            name='alcohol_degree',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='img_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='recipe',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.CreateModel(
            name='TodayDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.ForeignKey(db_column='today_drink', on_delete=django.db.models.deletion.CASCADE, to='api.cocktail')),
            ],
        ),
    ]
