# Generated by Django 3.2.17 on 2023-02-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='glass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cocktail', to='api.glass'),
        ),
    ]
